version: '2'
services:
  mariadb:
    image: bitnami/mariadb:10.1
    environment:
      - MARIADB_USER=moodle
      - MARIADB_DATABASE=moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  moodle:
    image: bitnami/moodle:3
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_NAME=moodle
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - '.:/bitnami/moodle/local/translate'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local